### ISSUE TITLE
Cannot read property 'options' of undefined

### ISSUE THREAD

**Issue by AidanNichol** [UXtemple/redux-pouch#1]
Uncaught TypeError: Cannot read property 'options' of undefined
findAll @ adapter.js:44
(anonymous function) @ middleware.js:49 (redux-pouch)
anonymous function) @ index.js:67 (redux-promise)
(anonymous function) @ index.js:12 (redux-thunk)
componentDidMount @ component.js:76

It appears to be expecting a parameter _ref to be passed when acton findAll is dispatched from componentDidMount but it isn't getting passed through by the middleware.

I pulled the code yesterday so should be the latest version

**Comment by AidanNichol** [comment]
changing adaoter.es6:25 to
const findAll = (db, {options}={}) => db
seems to fix the problem

**Comment by dariocravero** [comment]
Well spotted @AidanNichol, thanks! The adapter needs to be tested to prevent all of that :/. I'm in between adding [pouchdb-authentication](https://github.com/nolanlawson/pouchdb-authentication) and will refactor the adapter afterwards. That refactor will include tests and this fix. Should be out later on this week, is that alright?

**Comment by AidanNichol** [comment]
That will be fine. As it happens I’m taking a good look at Cerebral as an alternative to Redux.

**Comment by dariocravero** [comment]
Good stuff :)
